### ISSUE TITLE
Transition when entering is wrong if the component is aligned in center

### ISSUE THREAD

**Issue by jonahbgoode** [braposo/react-text-loop#11]
If the <TextLoop> is aligned in the center i.e. text-align: center; the transition acts abnormally.

**Comment by jinhyuk** [comment]
@jonahbgoode I wrapped text with a fixed-width div element for center.

```jsx
import React from 'react';
import styled from 'styled-components';
import TextLoop from 'react-text-loop';

const Text = styled.div`
  width: 500px;
  text-align: center;
`;

const App = props => (
  <TextLoop>
    <Text>Hello</Text>
    <Text>World</Text>
  </TextLoop>
)
```

**Comment by braposo** [comment]
Hi @jonahbgoode! I'm really really sorry I didn't see this before, I missed it completely on my notifications 😞 

Thanks @jinhyuk for taking the time to help out. To give you a more detailed answer, the way `TextLoop` component is currently implemented is optimised for the cases where it's used within a sentence so it tries to be left aligned with the current text.

I've created a sandbox so you can play a bit with the proposed solution (used glamorous instead of styled-components but it's the same principle): https://codesandbox.io/s/2z7v4ovrn0

I'm planning some improvements to the library in the next few weeks so I'll keep this open to have a better look at it and see if there's a way to make it easier to use in these situations. Thanks again for opening the issue!

**Comment by braposo** [comment]
Closing this now as the solution has been given.
