### ISSUE TITLE
Text spills beyond containing div

### ISSUE THREAD

**Issue by Chenzilla** [braposo/react-text-loop#14]
When the animation is turned on, the text breaks out of the containing div as a single line, regardless of any max-width or width style constraints placed upon the containing div.

**Comment by braposo** [comment]
Hi @Chenzilla, thanks for creating the issue! 

The original use case for this library was to do a single/multi word animation inside a sentence, and that's why it was implemented to always [force it to be in a single line](https://github.com/EDITD/react-text-loop/blob/69680d0d0fc32e21c87c5e395e262295b5bf0d8a/src/components/TextLoop.jsx#L113). 

I was thinking about adding an `inline` prop to disable it if needed. Would that solve your issue? You can [check this sandbox](https://codesandbox.io/s/r50n86om94) with a preview of what it would look like.

**Comment by Chenzilla** [comment]
@braposo this would be perfect :)

**Comment by braposo** [comment]
After [v2.0.0](https://github.com/braposo/react-text-loop/releases/tag/v2.0.0) release, `noWrap` prop can now be used to disable the default behaviour.
