### ISSUE TITLE
Animating characters in sequence

### ISSUE THREAD

**Issue by oyeanuj** [braposo/react-text-loop#15]
Hi @braposo, while using this library I found myself wanting to animate the characters in sequence rather than the whole word. A good example can be found on first fold of https://3dro.ps.

Thoughts on if and how that is something that could be a part of this library?

**Comment by braposo** [comment]
Hey @oyeanuj, you can actually do that by just using each letter as the children and building a word out of `<TextLoop>` components. Here's a sandbox with that example https://codesandbox.io/s/zzlx939zpp

As you'll quickly notice it will be out of sync after a bit but that's just because of the different speed setting. This will be fixed once we add the `delay` prop instead so all of them have the same animation time, just start at different times. 

Is that what you were looking for?

**Comment by oyeanuj** [comment]
@braposo That is interesting, I hadn't thought of that strategy. I think the first initial replacement animation would be close to the effect that I was hoping for - so I guess will wait until the `delay` prop is added, so that we'll be able to replicate that initial effect.

Thank you for the quick response!

**Comment by braposo** [comment]
This is now possible with the `delay` prop in [v2.0.0](https://github.com/braposo/react-text-loop/releases/tag/v2.0.0)

**Comment by ajayaj2001** [comment]
hey @braposo  the above codesandbox code is not found  ,i'm also having same problem can you share the code.
